### ISSUE TITLE
Configure diagnostic settings failed.

### ISSUE THREAD

**Issue by v-minh1** [Azure-Samples/animal-rescue#5] opened 2022-04-21 07:20 UTC
![image](https://user-images.githubusercontent.com/41893881/164397240-011416bd-7b65-4622-a3d9-e4fee1c1c862.png)
![image](https://user-images.githubusercontent.com/41893881/164397365-19487cd2-cd87-467b-95f7-4174bf9c77ec.png)

**Comment by maly7** [comment] 2022-05-12 20:53
Thanks, @v-minh1. This error would indicate that the `--resource` option was missing. Can you confirm that the variable `SPRING_CLOUD_RESOURCE_ID` has been set before running this command?

The preceding command shows how to set this variable:
```shell
export SPRING_CLOUD_RESOURCE_ID=$(az spring-cloud show \
    --name ${SPRING_CLOUD_SERVICE} \
    --resource-group ${RESOURCE_GROUP} | jq -r '.id')
```

**Comment by v-minh1** [comment] 2022-07-07 07:39
@maly7  Yes, the variable SPRING_CLOUD_RESOURCE_ID has been set before running this command.
![image](https://user-images.githubusercontent.com/41893881/177718765-5a5525cc-6f95-4c6a-90ee-6862d8a29d39.png)

**Comment by maly7** [comment] 2022-07-07 13:32
@v-minh1, would you try setting `export MSYS_NO_PATHCONV=1`? I think this is caused by git bash misinterpreting resource IDs as system file paths and setting this environment variable should fix it.

**Comment by qingc** [comment] 2022-07-08 07:17
@maly7 Thanks! It works after setting `export MSYS_NO_PATHCONV=1`. Could you add this to the doc to avoid same issue in the future? Then we're good to close this issue.

**Comment by maly7** [comment] 2022-07-08 14:55
Thanks, @qingc!

**Closed as completed** 2022-07-08 14:55 UTC
